# Generated by Django 4.0.6 on 2022-07-09 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_song_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artists',
        ),
    ]
